name: Build and Push to Google Container Registry

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
    build-push-container:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v4'

            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                  credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'

            - name: 'Docker auth'
              run: |-
                  gcloud auth configure-docker gcr.io --quiet

            - name: 'Build image'
              run: docker build . --file Dockerfile --tag gcr.io/${{ secrets.PROJECT_ID }}/next-log-parser

            - name: 'Push image'
              run: docker push gcr.io/${{ secrets.PROJECT_ID }}/next-log-parser
