name: Build and Push to Artifact Registry

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    REGION: ${{ secrets.REGION }}
    GAR_LOCATION: ${{ secrets.GAR_LOCATION }}

jobs:
    build-push-artifact:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v4'

            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                  credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'

            - name: 'Use gcloud CLI'
              run: 'gcloud info'

            - name: 'Docker auth'
              run: |-
                  gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

            - name: 'Build image'
              run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}
              working-directory: $GITHUB_WORKSPACE

            - name: 'Push image' # Fixes the syntax error
              run: docker push ${{ env.GAR_LOCATION }}
